# Site settings
title: shoya.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shoya.io" # the base hostname & protocol for your site
fullurl: "https://shoya.io" # https://stackoverflow.com/questions/40668302/jekyll-host-option-overriding-site-url
destination: _site
permalink: /blog/:title/
markdown: kramdown
popular: ["Paletta", "zebra", "cookpad_internship", "hatena_intern", "internet_black_market", "long_shadow"]
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
