# Site settings
title: Shoya Ishimaru
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shoya.io" # the base hostname & protocol for your site
permalink: /blog/:title/
markdown: kramdown
popular: ["Paletta", "cookpad_internship", "long_shadow", "hatena_intern", "life_in_germany", "internet_black_market"]